#!/usr/bin/env python

import struct
import sys
import json
import sys

from commandhandler import CommandHandler

sys.stderr = open('/tmp/goopg.err', 'a')


def send_message(message):
    """Helper function that sends a message to the webapp."""
    # Write message size.
    sys.stdout.write(struct.pack('I', len(message)))
    # Write the message itself.
    sys.stdout.write(message)
    sys.stdout.flush()


def read_thread_func():
    """Thread that reads messages from the webapp."""
    #message_number = 0
    handler = CommandHandler()
    while 1:
        # Read the message length (first 4 bytes).
        text_length_bytes = sys.stdin.read(4)

        # Unpack message length as 4 byte integer.
        text_length = struct.unpack('i', text_length_bytes)[0]

        # Read the text (JSON object) of the message.
        raw_text = sys.stdin.read(text_length).decode('utf-8')
        command = json.loads(raw_text)
        result = handler.parse(command)
        if result:
            command['result'] = result
            command = json.dumps(command)
            send_message(command)


if __name__ == '__main__':
    read_thread_func()
    sys.exit(0)
